[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for expected environment variables
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,PORT,MONGODB_URI,OPENAI_API_KEY,SESSION_SECRET"
  # Alternative: Disable secrets scanning entirely (less secure but will work)
  # SECRETS_SCAN_ENABLED = "false"

# Production environment settings
[context.production]
  command = "npm run build"
  
  [context.production.environment]
    NODE_ENV = "production"

# Deploy previews (branch deployments)
[context.deploy-preview]
  command = "npm run build"

# Branch deployments
[context.branch-deploy]
  command = "npm run build"

# Build settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; media-src 'self';"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# API Functions (if you plan to use Netlify Functions later)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
