[phases.setup]
nixPkgs = ["python311", "rustc", "cargo"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.prod.txt"
]

[start]
cmd = "python therapy_service.py"

